[context.production.environment]
  NODE_VERSION = "14.17.0"
  YARN_VERSION = "1.22.10"

[context.deploy-preview.environment]
  NODE_VERSION = "14.17.0"
  YARN_VERSION = "1.22.10"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200